// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTLjusoMK4a4bLdE17EkrQnGRmnDi9ITY',
    appId: '1:329955242254:web:51f364433170d40146675f',
    messagingSenderId: '329955242254',
    projectId: 'applemusic-39693',
    authDomain: 'applemusic-39693.firebaseapp.com',
    storageBucket: 'applemusic-39693.appspot.com',
    measurementId: 'G-QVS30XBCHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAHi0CFeFFAGSXvCYC5zbJUimHIz7kV50',
    appId: '1:329955242254:android:e717add6069c900b46675f',
    messagingSenderId: '329955242254',
    projectId: 'applemusic-39693',
    storageBucket: 'applemusic-39693.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTCviB2nzO0nGoXQQ4tdgzROxgCOJa5So',
    appId: '1:329955242254:ios:7bd500ba85e509a546675f',
    messagingSenderId: '329955242254',
    projectId: 'applemusic-39693',
    storageBucket: 'applemusic-39693.appspot.com',
    iosBundleId: 'com.example.applemusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTCviB2nzO0nGoXQQ4tdgzROxgCOJa5So',
    appId: '1:329955242254:ios:c09679434c0e691d46675f',
    messagingSenderId: '329955242254',
    projectId: 'applemusic-39693',
    storageBucket: 'applemusic-39693.appspot.com',
    iosBundleId: 'com.example.applemusic.RunnerTests',
  );
}
